suchseite = new Array();
suchseite[0] = new Array("Rumex Forum", 'forum.html');
suchseite[1] = new Array("Impressum", 'impressum.html');
suchseite[2] = new Array("IT Bayer's rumex", 'index.html');
suchseite[3] = new Array("Abo Seite - Newsletter - RSS Feed", 'rss.html');
suchseite[4] = new Array("Suche", 'suche.html');
suchseite[5] = new Array("Beschreibung des Rumex Baukastens", 'beschreibung.html');
suchseite[6] = new Array("Historie", 'historie.html');
suchseite[7] = new Array("Start", 'start.html');
