# 
# Makefile
#

include ../bin/user.config.makefile
include ../bin/sys.config.makefile
include ../bin/main.makefile
include ../bin/pandoc_html.makefile
include ../bin/pandoc_pdf.makefile
include ../bin/bilder.makefile
